version: "3.5"

services:
  db:
    image: postgres:13.3-alpine
    container_name: dbpostgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: aluraflix
      POSTGRES_USER: adriano
      POSTGRES_PASSWORD: adriano

volumes:
  db-data:
