version: "3.5"

services:
  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - m2-test:/root/.m2
    env_file:
      - .env-test

volumes:
  m2-test:
