version: "3.5"

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13.3-alpine
    container_name: dbpostgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${DATASOURCE_DATABASE}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

volumes:
  db-data:
